AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**/*
    - db/**/*
    - doc/**/*
    - config/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*

Documentation:
  Enabled: false

# LineLength:
#   Enabled: false

# MethodLength
#   Enabled: false
