findNestedDependencies: true
modules:
  - name: 'main'
paths:
  'backbone': 'backbone-min'
  'bbrsync': 'backbone-react-sync-min'
  'chaplin': 'chaplin-min'
  'jquery': 'jquery-2.1.1-min'
  'react': 'react-0.10.0'
  'underscore': 'underscore-min'
preserveLicenseComments: false
shim:
  # 'bootstrap/affix':
    # deps: ['jquery']
  # 'bootstrap/alert':
    # deps: ['jquery']
  # 'bootstrap/button':
    # deps: ['jquery']
  # 'bootstrap/carousel':
    # deps: ['jquery']
  # 'bootstrap/collapse':
    # deps: ['jquery', 'bootstrap/transition']
  # 'bootstrap/dropdown':
    # deps: ['jquery']
  # 'bootstrap/modal':
    # deps: ['jquery']
  # 'bootstrap/popover':
    # deps: ['jquery', 'bootstrap/tooltip']
  # 'bootstrap/scrollspy':
    # deps: ['jquery']
  # 'bootstrap/tab':
    # deps: ['jquery']
  # 'bootstrap/tooltip':
    # deps: ['jquery']
  # 'bootstrap/transition':
    # deps: ['jquery']
  'js-routes':
    exports: 'Routes'
wrap: true
